# bermiz.github.io jekuyl config

## uncomment when beremiz.org CNAME targets github pages 
# title: beremiz.org

author:
  name: "Beremiz SAS, France"
  url: https://beremiz.fr
email: webmaster@beremiz.org
tagline: "Beremiz home"
description: "Beremiz is Open Source PLC. It brings Free Software IDE (GPL) and Runtime (LGPL) for machine automation, conforming to IEC-61131."
baseurl: ""
url: "https://beremiz.org"
github_username: beremiz
show_excerpts: true
theme: minima

header_pages:
  - about.md
  - usecases/index.md
  - doc/index.md
  - get.md
  - support.md
